### PR TITLE
rewriting feedback module to hide private variables

### PR DESCRIPTION
**Pull request by peterBrxwn**

### CODE REVIEW

**Review by ijunaid — APPROVED** [review]

**Comment by turtledreams** [comment]
[[RN] Look into having private information in the SDK and how to hide it](https://trello.com/c/ZSKrdmXO/880-rn-look-into-having-private-information-in-the-sdk-and-how-to-hide-it)

**Review by turtledreams — APPROVED** [review]

**Review by turtledreams — CHANGES_REQUESTED** [review]
I fixed the conflict so now you will have to import the logger at feedback module and use its for logging. also add some logs for when a function is called instead of just logging errors. then also you would not need the countly instance anymore in Feedback constructor (as it was only used for logs)

**Comment by peterBrxwn** [comment]
@turtledreams I have updated the feedback module. Kindly review.

**Review by turtledreams — CHANGES_REQUESTED** [review]
Looking good 👍 
Do we have examples for all these functions here at example app?
This is a nice opportunity to add them now.
Even a better opportunity to create a new page for feedback widgets and add all feedback related examples (legacy and new) there where we can do tests for all widgets.
Possible?

**Pull request merged**
